disable github action and use githook instead so that you dont have to do a pull after a push

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,19 @@
 #!/bin/sh
+
+# set -x: Enables debug mode, which prints each command before executing it. This can be helpful for debugging.
+# set -x 
+
+# set -e: Exits the script if any command in the script fails (i.e., returns a non-zero exit code).
+
+set -e
+
 echo "Running pre-commit yamllint checks..."
 yamllint -c .yamllint .
 
 # Check if there are changes in services-available/**/*.yml
 if [ -n "$(git diff --cached --name-only --diff-filter=ACMRTUXB services-available/**/*.yml)" ]; then
   # Call the script to generate SERVICES.md
-  .github/scripts/generate-services-markdown.sh
+  .githooks/generate-services-markdown.sh
 
   # Add SERVICES.md to the commit
   git add ./SERVICES.md
